# solaris.conf for GSI builds
SPOOF_PROPS='true'
BRAND='Android'
MANUFACTURER='unknown'
DEVICE='generic_arm64'
MODEL='AOSP on ARM64'
MARKETNAME='AOSP on ARM64'
FINGERPRINT='google/husky_beta/husky:15/BP11.241025.006/12620009:user/release-keys'
