# solaris.conf for Redmi Note 12 4G
SPOOF_PROPS='true'
BRAND='Redmi'
MANUFACTURER='Xiaomi'
DEVICE='tapas'
MODEL='23021RAAEG'
MARKETNAME='Redmi Note 12'
FINGERPRINT='Nothing/Galaga/Galaga:16/BP2A.250605.031.A3/2512182326:user/release-keys'