# solaris.conf for Redmi Note 7
SPOOF_PROPS='true'
BRAND='Xiaomi'
MANUFACTURER='Xiaomi'
DEVICE='lavender'
MODEL='Redmi Note 7'
MARKETNAME='Redmi Note 7'
FINGERPRINT='Nothing/Galaga/Galaga:16/BP2A.250605.031.A3/2512182326:user/release-keys'