# solaris.conf for Nothing Phone (1)
SPOOF_PROPS='true'
BRAND='Nothing'
MANUFACTURER='Nothing'
DEVICE='Spacewar'
MODEL='A063'
MARKETNAME='Nothing Phone (1)'
FINGERPRINT='Nothing/Spacewar/Spacewar:15/AQ3A.240929.001/2512310041:user/release-keys'
